---
title: "Ngundeng Analytics Technologies - Time Series Analysis of the Real GDP of Mexico"
format: html
---

```{r}
library(tidyverse)
library(lubridate)
library(fpp3)
```
```{r}
#Warning: x = 'NGDPRNSAXDCSSD', get = 'economic.data': Error in getSymbols.FRED(Symbols = "NGDPRNSAXDCSSD", env = <environment>, : Unable to import “NGDPRNSAXDCSSD”.
#cannot open the connection
```

```{r}
gdp <- gdp |> 
  mutate(date = yearquarter(date)) |> 
  as_tsibble(
    index = date,
    key   = symbol
  )

gdp
```

```{r}
gdp_train <- gdp |> 
  filter_index(. ~ "2021 Q4") |>
  as_tsibble(index = date, key = symbol)

gdp_train

```

```{r}
p <- gdp_train |> 
  autoplot(price) +
  labs(
    title = "Time series plot of the Real GDP for Mexico",
    y = "GDP"
  )
 
ggplotly(p, dynamicTicks = TRUE) |> 
  rangeslider()
```

```{r}
gdp_train |> 
  gg_season(price) |> 
  ggplotly()
```

```{r}
gdp_train |> 
  model(stl = STL(price, robust = TRUE)) |> 
  components() |> 
  autoplot() |> 
  ggplotly()
```

```{r}
gdp_train |> 
  autoplot(log(price)) +
  ggtitle("Log of the Real GDP of Mexico")
```

```{r}
gdp_train |> 
  model(stl = STL(log(price) ~ season(window = "periodic"), robust = TRUE)) |> 
  components() |> 
  autoplot() |> 
  ggplotly()
```

```{r}
gdp_fit <- gdp_train |> 
  model(
    snaive = SNAIVE(log(price)),
    drift  = RW(log(price) ~ drift())
  )
```

```{r}
gdp_fit |> 
  select(snaive) |> 
  gg_tsresiduals() +
  ggtitle("Residuals Diagnostics for the Seasonal Naïve Model")
```

```{r}
gdp_fit |> 
  select(drift) |> 
  gg_tsresiduals() +
  ggtitle("Residuals Diagnostics for the Drift Model")
```

```{r}
gdp_fit |> 
  augment() |> 
  features(.innov, ljung_box, lag = 24, dof = 0)
```

```{r}
gdp_train_accu <- accuracy(gdp_fit) |> 
  arrange(MAPE)
gdp_train_accu |> 
  select(symbol:.type, MAPE, RMSE, MAE, MASE)
```

```{r}
gdp_fit_dcmp <- gdp_train |> 
      model(
        stlf = decomposition_model(
          STL(log(price) ~ season(window = "periodic"), robust = TRUE),
          RW(season_adjust ~ drift())
        )
      )

gdp_fit_dcmp
```

```{r}
gdp_fit <- gdp_fit |> 
  left_join(gdp_fit_dcmp)
```

```{r}
gdp_fit |> 
  accuracy() |> 
  select(symbol:.type, MAPE, RMSE, MAE, MASE) |> 
  arrange(MAPE)
```

```{r}
gdp_fit |> 
  select(stlf) |> 
  gg_tsresiduals()
```

```{r}
gdp_fit |> 
  augment() |> 
  features(.innov, ljung_box)
```

```{r}

gdp_h_fc <- 8
gdp_fc <- gdp_fit |> 
  forecast(h = gdp_h_fc)

gdp_fc
```

```{r}
gdp_fc |> 
  autoplot(gdp) +
  facet_wrap(~.model, ncol = 1)
```

```{r}
gdp_fc |> 
  filter(.model == "stlf") |> 
  autoplot(gdp)
```

```{r}
gdp_fc |> 
  accuracy(gdp) |> 
  select(.model:.type, MAPE, RMSE, MAE, MASE) |> 
  arrange(MAPE)
```

```{r}
gdp_fit2 <- gdp |> 
  model(
    stlf = decomposition_model(
          STL(log(price) ~ season(window = "periodic"), robust = TRUE),
          RW(season_adjust ~ drift())
        )
  )
gdp_fit2
```

```{r}
gdp_fc_fut <- gdp_fit2 |> 
  forecast(h = gdp_h_fc)
gdp_fc_fut
```

```{r}
gdp_fc_fut |> 
  autoplot(gdp) +
  facet_wrap(~.model, ncol = 1)
```
```{r}
## feb 18th exercise:
library(tidyverse)
library(fpp3)
```

```{r}
gas_train <- aus_production |> 
  filter_index(. ~ "2007 Q2")

gas_train
```

```{r}
gas_train |> 
  autoplot(Gas)
```

```{r}
gas_lambda <- gas_train |> 
  features(Gas, guerrero) |> 
  pull()

gas_lambda
```
```{r}
gas_train |> 
  autoplot(box_cox(Gas, gas_lambda))
```

```{r}
gas_train |> 
  model(
    stl = STL(box_cox(Gas, gas_lambda), robust = TRUE)
  ) |> 
    components() |> 
  autoplot()
```
```{r}
gas_fit <- gas_train |> 
  model(
    media = MEAN(box_cox(Gas, gas_lambda)),
    naive = NAIVE(box_cox(Gas, gas_lambda)),
    snaive = SNAIVE(box_cox(Gas, gas_lambda)),
    drift = RW(box_cox(Gas, gas_lambda) ~ drift())
  )

gas_fit
```
```{r}
gas_aug <- gas_fit |> 
  augment()

gas_fit |> 
  select(media) |>
  gg_tsresiduals() +
  labs(
    title = "Residuos del modelo media"
  )
```

```{r}
gas_aug |> 
  ggplot(aes(x = Quarter, y = .innov)) + 
  geom_line() +
  facet_wrap(vars(.model), scales = "free_y") + 
  labs(
    title = "Innovaciones de los modelos benchmark"
  )
```

```{r}
imports <- tidyquant::tq_get(
  x = "MAUINSA",
  get = "economic.data",
  from = "1993-01-01",
  to = "2025-10-01"
  
  
) |> 
  mutate(date = yearmonth(date) #
  ) |> as_tsibble(
    index = date)

imports

```

```{r}
1. Se selecciona `get = "economic.data"` para obtener datos económicos de la base de datos FRED (Federal Reserve Economic Data).
2. Se convierte la columna `date` a un formato de fecha utilizando `yearmonth()` de la librería `lubridate`, lo que facilita el manejo de series temporales mensuales.

## Instrucciones 

Realizar un pronostico a 14 meses (hasta diciembre de 2025). Realizar el flujo de pronóstico completo, desde la exploración de los datos, el ajuste de modelos y la evaluación de su desempeño.
```

```{r}

h = 14 
imports_train <- imports |> 
  slice(1:(n() - h))

imports_train
```

```{r}
imports_train |> 
  autoplot(price) +
  labs(
    title = "Time series plot of the Auto Imports of Mexico",
    y = "Imports"
  )
```
```{r}
library(plotly)
library(fpp3)
```

```{r}
imports_train |> 
  gg_season(price) |> 
  ggplotly()
```




```{r}
imports_train |> 
  autoplot(log(price))
```
```{r}

```


```{r}
price_lambda <- imports_train |> 
  features(price, guerrero) |> 
  pull()
price_lambda
```

```{r}


model_fit <- imports_train |> 
  model(
    media = MEAN(box_cox(price, price_lambda)),
    naive = NAIVE(box_cox(price, price_lambda)),
    snaive = SNAIVE(box_cox(price, price_lambda)),
    drift = RW(box_cox(price, price_lambda) ~ drift())
  )

model_fit
```
```{r}
imports_train |> 
  autoplot(box_cox(price, price_lambda))
```
```{r}
imports_train |> 
  model(
    stl = STL(box_cox(price, price_lambda), robust = TRUE)
  ) |> 
    components() |> 
  autoplot()
```
```{r}
imports_fit <- imports_train |> 
  model(
    media = MEAN(box_cox(price, price_lambda)),
    naive = NAIVE(box_cox(price, price_lambda)),
    snaive = SNAIVE(box_cox(price, price_lambda)),
    drift = RW(box_cox(price, price_lambda) ~ drift())
  )

imports_fit
```

```{r}
imports_aug <- imports_fit |> 
  augment()


imports_fit |>
  select(media) |>
  gg_tsresiduals() +
  labs(
    title = "Residuos del modelo media"
  )
```

```{r}
imports_aug |> 
  ggplot(aes(x = date, y = .innov)) + 
  geom_line() +
  facet_wrap(vars(.model), scales = "free_y") + 
  labs(
    title = "Innovaciones de los modelos benchmark"
  )
```

```{r}
imports_fit_stl <- imports_train |> 
  model(
    stlf = decomposition_model(
      STL(box_cox(price, price_lambda), robust = TRUE),
      SNAIVE(season_year),
      RW(season_adjust ~ drift())
    )
  )

imports_fit_stl
```


```{r}
imports_fit_stl |> 
  gg_tsresiduals()
```
```{r}
imports_fit_todos <- imports_train |> 
  model(
    media = MEAN(box_cox(price, price_lambda)),
    naive = NAIVE(box_cox(price, price_lambda)),
    snaive = SNAIVE(box_cox(price, price_lambda)),
    drift = RW(box_cox(price, price_lambda) ~ drift()),
    stlf = decomposition_model(
      STL(box_cox(price, price_lambda), robust = TRUE),
      SNAIVE(season_year),
      RW(season_adjust ~ drift())
    )
  )
imports_fit_todos
```


```{r}
imports_fc_todos <- imports_fit_todos |> 
  forecast(h = "5 years")

imports_fc_todos
```
```{r}
imports_fc_todos |> 
  autoplot(imports) +
  facet_wrap(vars(.model), scales = "free_y")
```

```{r}
imports_fc_todos |> 
  autoplot(imports, level = NULL, linewidth = 1)
```
```{r}
imports_fc_todos |> 
  accuracy(imports) |> 
  arrange(RMSE)
```

```{r}
imports |> 
  model(
    drift = RW(box_cox(price, price_lambda))
  ) |> 
    forecast(h = "3 years") |>
    autoplot(imports)
```

